#!/usr/bin/env python3
"""
Configure MusicMaster API credentials.

Usage:
    # Full setup
    python scripts/setup_config.py \\
        --spotify-id=CLIENT_ID \\
        --spotify-secret=CLIENT_SECRET \\
        --lastfm-key=API_KEY

    # Partial setup (Last.fm only)
    python scripts/setup_config.py --lastfm-key=API_KEY

    # Partial setup (Last.fm + Qobuz — password prompted securely)
    python scripts/setup_config.py \\
        --lastfm-key=API_KEY \\
        --qobuz-email=EMAIL

Creates/updates .env file with API credentials.
Services not specified will remain unconfigured (or keep existing values).
"""

import argparse
import getpass
import sys
import os
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from lib.preferences import Preferences


def get_skill_dir():
    return Path(__file__).parent.parent.absolute()


def load_existing_env() -> dict:
    """Load existing .env values if present."""
    env_file = get_skill_dir() / ".env"
    existing = {}

    if env_file.exists():
        with open(env_file, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    existing[key.strip()] = value.strip()

    return existing


def main():
    parser = argparse.ArgumentParser(
        description="Configure MusicMaster API credentials",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Last.fm only (free, no OAuth needed)
  python scripts/setup_config.py --lastfm-key=abc123

  # Last.fm + Qobuz (discovery + downloads, password prompted securely)
  python scripts/setup_config.py \\
      --lastfm-key=abc123 \\
      --qobuz-email=user@example.com

  # Full setup (all services)
  python scripts/setup_config.py \\
      --spotify-id=abc123 \\
      --spotify-secret=xyz789 \\
      --lastfm-key=def456

Where to get credentials:
  Spotify: https://developer.spotify.com/dashboard
  Last.fm: https://www.last.fm/api/account/create
"""
    )

    # All credentials are optional
    parser.add_argument("--spotify-id", help="Spotify Client ID")
    parser.add_argument("--spotify-secret", help="Spotify Client Secret")
    parser.add_argument("--spotify-redirect", default="http://127.0.0.1:8888/callback",
                        help="Spotify Redirect URI (default: http://127.0.0.1:8888/callback)")

    parser.add_argument("--lastfm-key", help="Last.fm API Key")

    parser.add_argument("--qobuz-email", help="Qobuz account email")
    parser.add_argument("--qobuz-quality", default="27",
                        help="Qobuz quality: 5=MP3, 6=FLAC 16bit, 7=24bit, 27=Hi-Res (default: 27)")
    parser.add_argument("--qobuz-path", default="~/Music/Qobuz",
                        help="Qobuz download path (default: ~/Music/Qobuz)")

    parser.add_argument("--tidal-quality", default="HiFi",
                        help="TIDAL quality: Normal/High/HiFi/Master/Max (default: HiFi)")
    parser.add_argument("--tidal-path", default="~/Music/TIDAL",
                        help="TIDAL download path (default: ~/Music/TIDAL)")

    args = parser.parse_args()

    # Check if at least one service is being configured
    has_spotify = args.spotify_id and args.spotify_secret
    has_lastfm = args.lastfm_key is not None
    # If Qobuz email provided, prompt for password securely (not via CLI arg)
    qobuz_password = None
    if args.qobuz_email:
        if sys.stdin.isatty():
            qobuz_password = getpass.getpass("Qobuz password: ")
        else:
            qobuz_password = sys.stdin.readline().strip()
        if not qobuz_password:
            print("Error: Qobuz password is required when --qobuz-email is specified.")
            print("Alternatively, edit the .env file directly to set QOBUZ_PASSWORD.")
            sys.exit(1)
    has_qobuz = args.qobuz_email and qobuz_password

    if not (has_spotify or has_lastfm or has_qobuz):
        print("Error: At least one service must be configured.")
        print()
        print("Examples:")
        print("  --lastfm-key=KEY                    (Last.fm only)")
        print("  --spotify-id=ID --spotify-secret=SECRET  (Spotify)")
        print("  --qobuz-email=EMAIL                        (Qobuz, password prompted)")
        sys.exit(1)

    # Load existing values to preserve them
    existing = load_existing_env()

    # Build .env content, merging with existing values
    lines = ["# MusicMaster Configuration", "# Generated by setup_config.py", ""]

    # Spotify
    lines.append("# === Spotify ===")
    if has_spotify:
        lines.append(f"SPOTIFY_CLIENT_ID={args.spotify_id}")
        lines.append(f"SPOTIFY_CLIENT_SECRET={args.spotify_secret}")
        lines.append(f"SPOTIFY_REDIRECT_URI={args.spotify_redirect}")
    elif existing.get("SPOTIFY_CLIENT_ID"):
        lines.append(f"SPOTIFY_CLIENT_ID={existing['SPOTIFY_CLIENT_ID']}")
        lines.append(f"SPOTIFY_CLIENT_SECRET={existing.get('SPOTIFY_CLIENT_SECRET', '')}")
        lines.append(f"SPOTIFY_REDIRECT_URI={existing.get('SPOTIFY_REDIRECT_URI', 'http://127.0.0.1:8888/callback')}")
    else:
        lines.append("# Not configured")
    lines.append("")

    # Last.fm
    lines.append("# === Last.fm ===")
    if has_lastfm:
        lines.append(f"LASTFM_API_KEY={args.lastfm_key}")
    elif existing.get("LASTFM_API_KEY"):
        lines.append(f"LASTFM_API_KEY={existing['LASTFM_API_KEY']}")
    else:
        lines.append("# Not configured")
    lines.append("")

    # Qobuz
    lines.append("# === Qobuz ===")
    if has_qobuz:
        lines.append(f"QOBUZ_EMAIL={args.qobuz_email}")
        lines.append(f"QOBUZ_PASSWORD={qobuz_password}")
        lines.append(f"QOBUZ_QUALITY={args.qobuz_quality}")
        lines.append(f"QOBUZ_DOWNLOAD_PATH={args.qobuz_path}")
    elif existing.get("QOBUZ_EMAIL"):
        lines.append(f"QOBUZ_EMAIL={existing['QOBUZ_EMAIL']}")
        lines.append(f"QOBUZ_PASSWORD={existing.get('QOBUZ_PASSWORD', '')}")
        lines.append(f"QOBUZ_QUALITY={existing.get('QOBUZ_QUALITY', '27')}")
        lines.append(f"QOBUZ_DOWNLOAD_PATH={existing.get('QOBUZ_DOWNLOAD_PATH', '~/Music/Qobuz')}")
    else:
        lines.append("# Not configured")
    lines.append("")

    # TIDAL (always write defaults, actual auth is via tiddl)
    lines.append("# === TIDAL ===")
    lines.append(f"TIDAL_QUALITY={args.tidal_quality}")
    lines.append(f"TIDAL_DOWNLOAD_PATH={args.tidal_path}")
    lines.append("# Note: TIDAL requires separate OAuth via 'tiddl auth login' command")

    env_content = "\n".join(lines) + "\n"

    # Write .env file
    env_file = get_skill_dir() / ".env"
    with open(env_file, 'w') as f:
        f.write(env_content)

    # Update preferences for configured services
    prefs = Preferences.load()

    print(f"Configuration saved to: {env_file}")
    print()
    print("Configured services:")

    if has_spotify:
        print(f"  [+] Spotify: {args.spotify_id[:8]}...")
        prefs.enable_service("spotify")
    elif existing.get("SPOTIFY_CLIENT_ID"):
        print(f"  [=] Spotify: {existing['SPOTIFY_CLIENT_ID'][:8]}... (unchanged)")
    else:
        print("  [-] Spotify: Not configured")

    if has_lastfm:
        print(f"  [+] Last.fm: {args.lastfm_key[:8]}...")
        prefs.enable_service("lastfm")
    elif existing.get("LASTFM_API_KEY"):
        print(f"  [=] Last.fm: {existing['LASTFM_API_KEY'][:8]}... (unchanged)")
    else:
        print("  [-] Last.fm: Not configured")

    if has_qobuz:
        print(f"  [+] Qobuz: {args.qobuz_email}")
        prefs.enable_service("qobuz")
    elif existing.get("QOBUZ_EMAIL"):
        print(f"  [=] Qobuz: {existing['QOBUZ_EMAIL']} (unchanged)")
    else:
        print("  [-] Qobuz: Not configured")

    print("  [-] TIDAL: Requires separate OAuth (run 'tiddl auth login')")

    print()
    if has_spotify:
        print("Next step: Run spotify_auth.py to complete Spotify OAuth")
    else:
        print("Next step: Run './run.sh status' to verify configuration")


if __name__ == "__main__":
    main()
